Repository SBD1/2025.1-Moonlighter, pull requests merged in 2025-05, with the labels that each got.

#6 [PR] - Criação das páginas 'Home' e 'Metodologia'
  apps/docs/docs/assets/Diagrama_Entidade_Relacionamento.svg
  apps/docs/docs/pages/Modulo1/Diagrama_Entidade_Relacionamento.md
  apps/docs/mkdocs.yml
Labels: documentation

#8 [PR] - Dicionário de Dados
  apps/docs/docs/pages/Modulo1/Dicionario.md
  apps/docs/mkdocs.yml
  package.json
Labels: documentation

#9 [PR] - Modelo Relacional
  apps/docs/docs/assets/mer.drawio.png
  apps/docs/docs/pages/Modulo1/Diagrama_Entidade_Relacionamento.md
  apps/docs/docs/pages/Modulo1/modelo_relacional.md
  apps/docs/mkdocs.yml
Labels: documentation

#10 Release
  apps/docs/docs/assets/Diagrama_Entidade_Relacionamento.svg
  apps/docs/docs/assets/mer.drawio.png
  apps/docs/docs/index.md
  apps/docs/docs/metodologia.md
  apps/docs/docs/pages/Modulo1/Diagrama_Entidade_Relacionamento.md
  apps/docs/docs/pages/Modulo1/Dicionario.md
  apps/docs/docs/pages/Modulo1/modelo_relacional.md
  apps/docs/mkdocs.yml
  package.json
Labels: documentation

#15 [PR]: Configurando Docker com PostgreSQL
  .gitignore
  README.md
  apps/sql/01-ddl.sql
  apps/sql/Query.sql
  docker-compose.yml
  package.json
Labels: enhancement

#17 [PR]: Criar Tabelas em SQL planejados no Modelo Relacional - DDL (Data Definition Language)
  apps/docs/docs/pages/Modulo1/Dicionario.md
  apps/sql/01-ddl.sql
  apps/sql/01-schemas.sql
  package.json
Labels: feat
