Repository SBD1/2025.1-Moonlighter, pull requests merged in 2025-07, with the labels that each got.

#37 [PR] - refactor(estabelecimento): loja Chápeu de Madeira agora vende armas e armaduras
  apps/cli/main.py
  apps/cli/src/pages/Estabelecimento/db_estabelecimento.py
  apps/cli/src/pages/Estabelecimento/inst_chapeu_de_madeira.py
  apps/cli/src/pages/Estabelecimento/inst_forja.py
  apps/cli/src/pages/IniciarJogo/iniciarJogo.py
  apps/sql/02-DML.sql
Labels: bug

#43 [PR] - Triggers e Store Procedure na Documentação
  apps/docs/docs/pages/Modulo3/StoredProcedures.md
  apps/docs/docs/pages/Modulo3/Triggers.md
  apps/docs/mkdocs.yml
Labels: documentation

#41 [PR] - Gerenciar a loja Moonlighter
  apps/cli/src/pages/Estabelecimento/db_moonlighter.py
  apps/cli/src/pages/Estabelecimento/moonlighter.py
  apps/cli/src/pages/IniciarJogo/iniciarJogo.py
  apps/cli/src/pages/IniciarJogo/inventario_interface.py
  apps/cli/src/pages/Tutorial/db_tutorial.py
  apps/sql/02-DML.sql
  apps/sql/04-Triggers.sql
  docker-compose.yml
Labels: feat
